### PR TITLE
122 revisit cicd

### PR DESCRIPTION
**Pull request by tschm**

### CODE REVIEW

**Comment by tschm** [comment]
@VanekPetr It seems you need to be more explicit when it comes to the type of index

**Comment by VanekPetr** [comment]
@tschm As you can see based on number of commits 😄, it became a bit tricky with randomness of MC scenarios (worked fine with fixed seed locally, but failed within GitHub action). Therefore I did a "fix" where I load scenarios from file instead. It's not perfect but we have a version v1 to start with :)

**Review by VanekPetr — APPROVED** [review]

**Comment by tschm** [comment]
@VanekPetr I did some reorg of your test resources. Now you don't have to do any TEST_DIR acrobatic. Please don't test for full accuracy between say two numpy arrays. Later we will test on different infrastructure and you can not maintain like 16 digits of accuracy. This problem should be addressed in a different merge request though. Please merge this one...

**Comment by VanekPetr** [comment]
> @VanekPetr I did some reorg of your test resources. Now you don't have to do any TEST_DIR acrobatic. Please don't test for full accuracy between say two numpy arrays. Later we will test on different infrastructure and you can not maintain like 16 digits of accuracy. This problem should be addressed in a different merge request though. Please merge this one...

It makes sense. Thank you. I am going to merge.

**Pull request merged**
